-- Grievance ticket table for MySQL (row-size safe: large fields as TEXT).
-- Use on UAT db_emp_backup_new; replaces src/main/resources/grievance-ticket-schema.sql for utf8mb4.

CREATE TABLE IF NOT EXISTS grievance_ticket (
  ticket_id BIGINT NOT NULL AUTO_INCREMENT,
  ticket_number VARCHAR(30) NULL,
  created_by_emp_id BIGINT NOT NULL,
  created_by_name VARCHAR(200) NULL,
  created_by_employee_id BIGINT NULL,
  created_by_department VARCHAR(200) NULL,
  created_by_phone VARCHAR(30) NULL,
  created_by_project_name VARCHAR(500) NULL,
  created_by_client_name VARCHAR(300) NULL,
  created_by_reporting_manager VARCHAR(200) NULL,
  subject VARCHAR(300) NOT NULL,
  category VARCHAR(150) NULL,
  sub_category VARCHAR(200) NULL,
  ticket_feature VARCHAR(200) NULL,
  issue_scenario VARCHAR(500) NULL,
  description TEXT NOT NULL,
  priority VARCHAR(30) NULL,
  status VARCHAR(40) NULL,
  assigned_to_emp_id BIGINT NULL,
  assigned_to_name VARCHAR(200) NULL,
  resolution_remarks TEXT NULL,
  resolution_category VARCHAR(150) NULL,
  action_taken TEXT NULL,
  resolved_by VARCHAR(200) NULL,
  resolution_date DATETIME NULL,
  resolution_doc_name VARCHAR(255) NULL,
  resolution_doc_path VARCHAR(1000) NULL,
  feedback_rating INT NULL,
  feedback_comments TEXT NULL,
  feedback_on DATETIME NULL,
  proof_file_name VARCHAR(255) NULL,
  proof_file_path VARCHAR(1000) NULL,
  created_on DATETIME NULL,
  updated_on DATETIME NULL,
  updated_by BIGINT NULL,
  is_active INT DEFAULT 1,
  closed_by_creator TINYINT(1) DEFAULT 0,
  PRIMARY KEY (ticket_id),
  UNIQUE KEY uq_grievance_ticket_number (ticket_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
