Employee.getEmployeeByEmpId= SELECT e.emp_id, e.aadhar , e.about_me,e.address,e.bank_account_no,e.bankifsccode,e.bank_name, \
e.blood_group,e.city,e.country,e.date_of_birth,e.date_of_joining,e.email,e.emergency_contact_mobile, \
e.employmentstatus,e.esic_number,e.father_name,e.gender,e.graduation,e.hobbies,e.landline,e.marital_status \
,e.mobile_no,e.mother_tongue,e.name,e.notice_period,e.official_mobile_no,e.pan_number,e.passport_number, \
e.permanent_address,e.pf_account_number,e.pincode,e.place_of_birth,e.post_graduation, \
e.previous_pf_account_number,e.relation,e.state,e.uan,e.views_on_organisation,e.year_of_grad, \
e.year_of_post_grad,e.emergency_contact_person,e.profile_image_name, \
em.name as manager, j.name as jobrole , d.name as department \
FROM employee e  \
INNER JOIN employee em ON e.manager_id = em.emp_id \
INNER JOIN job_role j ON j.job_role_id = e.job_role_id \
INNER JOIN department d ON d.dept_id = j.dept_id