#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_portal
spring.datasource.username=dbuser_emp_portal
spring.datasource.password=Apmosys@Emp123

poPortal.api.syncProject =http://192.168.21.175:8080/PoPortal/ishine/sync
poPortal.api.allProjects =http://192.168.21.175:8080/PoPortal/project/fixedCost/getAllProjects
resignation.consent.link =http://192.168.21.175:8081/employeeportal/#/user-exit/my-resignation/
rmg.project.approval.link=http://192.168.21.175:8081/employeeportal/#/user-team/resource-management/

#Delete Deparment PoPortal Sync Api
poPortal.api.syncDepartment = http://192.168.21.175:8080/PoPortal/ishine/updateDepartment/{id}
poPortal.api.isDepartmentUsed = http://192.168.21.175:8080/PoPortal/ishine/isDepartmentUsed/{deptId}
poPortal.api.deleteDepartment = http://192.168.21.175:8080/PoPortal/ishine/deleteDepartment/{id}

#Delete JobRole PoPortal Sync Api
poPortal.api.syncJobRole =http://192.168.21.175:8080/PoPortal/ishine/updateRole/{id}
poPortal.api.isJobRoleUsed = http://192.168.21.175:8080/PoPortal/ishine/isRoleUsed/{roleId}
poPortal.api.deleteJobRole = http://192.168.21.175:8080/PoPortal/ishine/deleteRole/{id}


file.location.image=/home/apmosys/tomcat-app/tomcat-emp/webapps/images/
file.location.document=/home/apmosys/tomcat-app/tomcat-emp/webapps/document/
helpFile.document.location = /home/apmosys/tomcat-app/tomcat-emp/webapps/helpDocument

file.location.documents.newsletter = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/newsletter

spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB


#Connection pool
spring.datasource.hikari.maximum-pool-size = 3000
#10 minutes wait time
spring.datasource.hikari.maxLifeTime : 180000

allEmployeeDSR.file.location=/home/apmosys/tomcat-app/tomcat-emp/webapps/

#Logging properties
logging.file.name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
logging.file.max-size=5MB
logging.pattern.rolling-file-name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal-%d{yyyy-MM-dd}.%i.log
logging.file.max-history=7