#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_portal
spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_backup
#spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_portal_latest

spring.datasource.username=dbuser_emp_portal
spring.datasource.password=Apmosys@Emp123

#reverse sync api on approve 
#poPortal.api.syncProject =http://192.168.21.175:8080/PoPortal/ishine/sync
poPortal.api.syncProject =http://172.1.3.174:8080/ishine/sync

#static OTP UAT
portal.static.otp = 12341234

#Shankh Portal Prod
poPortal.api.allProjects =https://shankh.apmosys.com/project/fixedCost/getAllProjects

#Shankh Portal Uat
#poPortal.api.allProjects =http://192.168.21.175:8080/PoPortal/project/fixedCost/getAllProjects

resignation.consent.link =http://192.168.21.175:8081/employeeportal/#/user-exit/my-resignation/
rmg.project.approval.link=http://192.168.21.175:8081/employeeportal/#/user-team/resource-management/
lms.redirectionURL=http://192.168.12.113/academy-lms/index.php/api/ishine
poPortal.api.realtimeProjectData = http://192.168.21.175:8080/api/poCrudOperationsInIshine
#QR code path
qr.storage.path=

#static OTP UAT
portal.static.otp = 12341234

#Delete Deparment PoPortal Sync Api
poPortal.api.syncDepartment = http://192.168.21.175:8080/PoPortal/ishine/updateDepartment/{id}
poPortal.api.isDepartmentUsed = http://192.168.21.175:8080/PoPortal/ishine/isDepartmentUsed/{deptId}
poPortal.api.deleteDepartment = http://192.168.21.175:8080/PoPortal/ishine/deleteDepartment/{id}

#Delete JobRole PoPortal Sync Api
poPortal.api.syncJobRole =http://192.168.21.175:8080/PoPortal/ishine/updateRole/{id}
poPortal.api.isJobRoleUsed = http://192.168.21.175:8080/PoPortal/ishine/isRoleUsed/{roleId}
poPortal.api.deleteJobRole = http://192.168.21.175:8080/PoPortal/ishine/deleteRole/{id}

file.location.upload-dir=/home/apmosys/tomcat-app/tomcat-emp/webapps/surveymedia/
file.location.image=/home/apmosys/tomcat-app/tomcat-emp/webapps/imagess/
file.location.document=/home/apmosys/tomcat-app/tomcat-emp/webapps/document/
helpFile.document.location = /home/apmosys/tomcat-app/tomcat-emp/webapps/helpDocument
file.location.releasenotesvideos= /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/video/
file.location.releasenotevideos= /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/video/
#file.location.releasenotesvideosOut=../../assets/videosTest/
file.location.documents.newsletter = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/newsletter
file.location.documents.travelDesk = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/travelDesk
file.location.documents.reimbursement = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/reimbursement
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

hr.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
finance.mail =  nidhi.pote@apmosys.com
#rmg.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
rmg.mail = rahul.singh@apmosys.com
billable.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
vp_mails = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
bd.mail = pratikshya.routray@apmosys.com
admin.mail = priyadarshini.singh@apmosys.com
billablechange.mail = prarthana.lenka@apmosys.com
ticket.mail = om.padwal@apmosys.com
admin.head = neha.borase@apmosys.com
#10 minutes wait time
#spring.datasource.hikari.maxLifeTime : 180000

#Connection pool
#maximum number of milliseconds that a client will wait for a connection
spring.datasource.hikari.connection-timeout = 150000
#minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.minimum-idle= 10
#maximum pool size
spring.datasource.hikari.maximum-pool-size= 3000
#maximum idle time for connection
spring.datasource.hikari.idle-timeout=100000
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
spring.datasource.hikari.max-lifetime= 180000


#For Travel Allowance data
level2Approver = 2

#For Reimbursement data
level2.Approver = 632
level2.ApproverMail = hrm2@apmosysemp.com
level3.Approver = 9
level3.ApproverMail = lituja.mishra@apmosysemp.com

allEmployeeDSR.file.location=/home/apmosys/tomcat-app/tomcat-emp/webapps/

#Logging properties
logging.file.name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
logging.file.max-size=5MB
logging.pattern.rolling-file-name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal-%d{yyyy-MM-dd}.%i.log
logging.file.max-history=7
#############################
leavetypeId = 1

#Correct mail password
mail.password = Welcome@2021

#InCorrect mail password
#mail.password = Welcome@2022
