#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.12.109:3306/db_emp_prod
spring.datasource.username=dbuser_emp_prod
spring.datasource.password=pBv&312_PROD



file.location.image=/data/tomcat-app/tomcat-emp/webapps/images


#Connection pool
spring.datasource.hikari.maximum-pool-size = 3000

#Logging properties
logging.file.name=/data/tomcat-app/tomcat-emp/webapps/logs/ishineportal.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
logging.file.max-size=5MB
logging.pattern.rolling-file-name=/data/tomcat-app/tomcat-emp/webapps/logs/ishineportal-%d{yyyy-MM-dd}.%i.log
logging.file.max-history=7