#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/employeeportal
spring.datasource.username=root
spring.datasource.password=Apmosys@123

file.location.image=/home/apmosys_2/Documents/employeePortal/images/

#Connection pool
spring.datasource.hikari.maximum-pool-size = 10