#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_emp_portal
spring.datasource.username=root
spring.datasource.password=Welcome@2024
spring.jpa.properties.hibernate.format_sql=true
#server.port= 9393

#static OTP UAT
portal.static.otp = 12341234

#QR code path
qr.storage.path=

file.location.image= D:/images/

#file.location.image=/home/apmosys/tomcat-app/tomcat-emp/webapps/images/
file.location.upload-dir=D:/surveymedia/
file.location.documents.interview=D:/uploads/interviews/
allEmployeeDSR.file.location=D:/documents

helpFile.document.location = /home/anurag.chaturvedi@apmosys.mahape/Desktop/Emp_portal_workspace/employeeportal_java/document/

file.location.releasenotesvideos = /home/anurag.chaturvedi@apmosys.mahape/Desktop/Production_build_workspace_06-08-24/employeeportal_java/video
file.location.releasenotevideos = /home/anurag.chaturvedi@apmosys.mahape/Desktop/Production_build_workspace_06-08-24/employeeportal_java/video

file.location.document=D:/document
#file.location.releasenotesvideos= /home/anurag.chaturvedi@apmosys.mahape/Desktop/17-jul-uat-workspace/employeeportal_java/videos/
#file.location.releasenotesvideosOut=../../assets/videosTest/
#file.location.releasenotevideos = /home/anurag.chaturvedi@apmosys.mahape/Desktop/17-jul-uat-workspace/employeeportal_java/videos/
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

poPortal.api.syncProject =http://192.168.21.175:8080/PoPortal/ishine/sync
poPortal.api.allProjects =http://192.168.21.175:8080/PoPortal/project/fixedCost/getAllProjects
resignation.consent.link =http://localhost:4200/#/user-exit/my-resignation/
rmg.project.approval.link=http://localhost:4200/#/user-team/resource-management/

#Delete Deparment PoPortal Sync Api
poPortal.api.syncDepartment = http://192.168.21.175:8080/PoPortal/ishine/updateDepartment/{id}
poPortal.api.isDepartmentUsed = http://192.168.21.175:8080/PoPortal/ishine/isDepartmentUsed/{deptId}
poPortal.api.deleteDepartment = http://192.168.21.175:8080/PoPortal/ishine/deleteDepartment/{id}

#Delete JobRole PoPortal Sync Api
poPortal.api.syncJobRole =http://192.168.21.175:8080/PoPortal/ishine/updateRole/{id}
poPortal.api.isJobRoleUsed = http://192.168.21.175:8080/PoPortal/ishine/isRoleUsed/{roleId}
poPortal.api.deleteJobRole = http://192.168.21.175:8080/PoPortal/ishine/deleteRole/{id}

#file.location.documents.newsletter = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/newsletter
file.location.documents.newsletter = D:/images/
file.location.documents.training = D:/documents/training/

hr.mail = priyadarshini.singh@apmosys.com
finance.mail = priyadarshini.singh@apmosys.com
rmg.mail = priyadarshini.singh@apmosys.com
billable.mail = priyadarshini.singh@apmosys.com
vp_mails = priyadarshini.singh@apmosys.com


EXPIRY_THRESHOLD_PERCENT = 80

#Connection pool
spring.datasource.hikari.maximum-pool-size = 3000
#10 minutes wait time
spring.datasource.hikari.maxLifeTime : 180000

#Correct mail password
mail.password = Welcome@2021

#InCorrect mail password
#mail.password = Welcome@2022

#Logging properties
logging.file.name=D:\\logs\\ishineportal.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
logging.file.max-size=5MB
logging.pattern.rolling-file-name=
logging.file.max-history=7