#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/employeeportal
spring.datasource.username=root
spring.datasource.password=Apmosys@123
#server.port= 9393

file.location.image=D:\\images\\

allEmployeeDSR.file.location=D:\\images\\

helpFile.document.location = /home/apmosys/policydoc

file.location.document=/home/apmosys/policydoc
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

#Connection pool
spring.datasource.hikari.maximum-pool-size = 10

#Logging properties
logging.file.name=D:\\logs\\ishineportal.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
logging.file.max-size=5MB
logging.pattern.rolling-file-name=D:\\logs\\ishineportal-%d{yyyy-MM-dd}.%i.log
logging.file.max-history=7