#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#staging
spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_backup

#uat
#spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_portal

#spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_portal
spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_backup
spring.datasource.username=dbuser_emp_portal
spring.datasource.password=Apmosys@Emp123

poPortal.api.syncProject =http://192.168.21.175:8080/PoPortal/ishine/sync
poPortal.api.allProjects =https://shankh.apmosys.com/project/fixedCost/getAllProjects
resignation.consent.link =http://192.168.21.175:8081/employeeportal/#/user-exit/my-resignation/
rmg.project.approval.link=http://192.168.21.175:8081/employeeportal/#/user-team/resource-management/
lms.redirectionURL=http://192.168.12.113/academy-lms/index.php/api/ishine

#QR code path
qr.storage.path=

#Delete Deparment PoPortal Sync Api
poPortal.api.syncDepartment = http://192.168.21.175:8080/PoPortal/ishine/updateDepartment/{id}
poPortal.api.isDepartmentUsed = http://192.168.21.175:8080/PoPortal/ishine/isDepartmentUsed/{deptId}
poPortal.api.deleteDepartment = http://192.168.21.175:8080/PoPortal/ishine/deleteDepartment/{id}

#Delete JobRole PoPortal Sync Api
poPortal.api.syncJobRole =http://192.168.21.175:8080/PoPortal/ishine/updateRole/{id}
poPortal.api.isJobRoleUsed = http://192.168.21.175:8080/PoPortal/ishine/isRoleUsed/{roleId}
poPortal.api.deleteJobRole = http://192.168.21.175:8080/PoPortal/ishine/deleteRole/{id}

file.location.upload-dir=/home/apmosys/tomcat-app/tomcat-emp/webapps/surveymedia/
file.location.image=/home/apmosys/tomcat-app/tomcat-emp/webapps/imagess/
file.location.document=/home/apmosys/tomcat-app/tomcat-emp/webapps/document/
helpFile.document.location = /home/apmosys/tomcat-app/tomcat-emp/webapps/helpDocument
file.location.releasenotesvideos= /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/video/
file.location.releasenotevideos= /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/video/
#file.location.releasenotesvideosOut=../../assets/videosTest/
file.location.documents.newsletter = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/newsletter

spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

hr.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
finance.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
rmg.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
billable.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
vp_mails = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com

#Connection pool
spring.datasource.hikari.maximum-pool-size = 3000
#10 minutes wait time
spring.datasource.hikari.maxLifeTime : 180000

allEmployeeDSR.file.location=/home/apmosys/tomcat-app/tomcat-emp/webapps/

#Logging properties
logging.file.name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
logging.file.max-size=5MB
logging.pattern.rolling-file-name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal-%d{yyyy-MM-dd}.%i.log
logging.file.max-history=7
