spring.profiles.active = local

#server.servlet.session.timeout=1
#hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.banner.location=classpath:banner.txt
application.version=2.0

default.password=Apmosys@123

## Leave Policy Reference Details
financialYear.startDate = 1
financialYear.startMonth = 4

#PO portal db details
po.db.url =jdbc:mysql://150.242.14.145:3306/PO_PORTAL
po.db.username =Jenkin
po.db.password =password

#Timesheet lock period
timesheet.lock.days = 31
timesheet.backdated.days = 30
timesheet.reconcile.days = 3

#static OTP
portal.static.otp = 12341234

idle.session.timeout=900

valid.attempt=5

#mail
mail.sender = ishine@apmosys.com
mail.password = Welcome@2021
mail.port = 587
mail.host = apmosys.icewarpcloud.in

#hr mail address
hr.mail = hr@apmosys.com

#noticePeriod & probationPeriod MailTrigger time
mailTrigger.time = 0 0 12 ? * *

#monthlyTimesheetExcelGenerator CronExpression
monthlyTimesheetExcelGenerator.expression = 0 0 4 2 * ?

#spring.jpa.properties.hibernate.generate_statistics=true