spring.profiles.active = prod
#hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.banner.location=classpath:banner.txt
application.version=2.0

default.password=Apmosys@123

## Leave Policy Reference Details
financialYear.startDate = 1
financialYear.startMonth = 4

#PO portal db details
po.db.url =jdbc:mysql://150.242.14.145:3306/PO_PORTAL
po.db.username =Jenkin
po.db.password =password

#Timesheet lock period
timesheet.lock.days = 3
timesheet.backdated.days = 60
timesheet.reconcile.days = 3

compoff.lock.days = 60
leave.backdated.lock.days = 60
leave.future.lock.days = 180

#Timesheet By Team member
timesheet.check.period = 30
maximum.timesheetCanBeFilledByMember = 2

#static OTP
portal.static.otp = 12341234

# OTP Timeout (Min)
otp.timeout.period = 1 

# User Idle Session timeout (Sec)
idle.session.timeout=900
revoke.reportee.leave.validity = 70

valid.attempt=5
usersession.inactive.timeout = 10

#mail
mail.sender = ishine@apmosys.com
mail.password = Welcome@2021
mail.port = 587
mail.host = apmosys.icewarpcloud.in

#hr mail address
hr.mail = hr@apmosys.com,hrm2@apmosys.com
finance.mail = finance@apmosys.com,accounts@apmosys.com
rmg.mail = rmgm1@apmosys.com,rmgm2@apmosys.com
billable.mail = bibhu@apmosys.com,pratima.b.nayak@apmosys.com,sangeeta@apmosys.com
#billable.mail = ar731829@gmail.com,anurag.chaturvedi@apmosys.com
#vp_mails = bishnu.rath@apmosys.com,sanjay.panda@apmosys.com,lalit.popli@apmosys.com,puspak.patnaik@apmosys.com,mohan.cherian@apmosys.com,lituja.mishra@apmosys.com,jhimly.hazra@apmosys.com,bansi.prasad@apmosys.com,manoj.sethi@apmosys.com,ashok.swaminathan@apmosys.com,prabhat.padhy@apmosys.com,pradeep.paidisetty@apmosys.com,mayuresh.potnis@apmosys.com,ramshankar.h@apmosys.com


#noticePeriod & probationPeriod MailTrigger time
mailTrigger.time = 0 0 12 ? * *
timesheetDefaulter.time = 0 0 14 ? * *

#monthlyTimesheetExcelGenerator CronExpression
monthlyTimesheetExcelGenerator.expression = 0 0 4 2 * ?
birthdaymail.cron.expression = 0 0 7 ? * *

CLleave.maxDays = 2

#   0 0 7 ? * *     //  this cron expression run daily on 7 O'clock at morning
#compOff_TAT = 0 0 7 ? * *
compOff_TAT = 0 50 15 09 01 ?

compOff_Expiration = 0 0 8 ? * *
#compOff_Expiration = 0 */3 * * * ?


#leaveMapToNewManager_cron = 0 0 8 ? * *

leaveMapToNewManager_cron = 0 50 15 09 01 ?

pip_reminder_mail = 0 0 8 ? * *

reminder_Mail_Date = 90

compOff_apply_withIn = 10

VP_mails = 0 30 10 ? * *

department_wise_billable_report = 0 35 16 ? * *
#department_wise_billable_report = 0 */2 * * * ?
#spring.jpa.properties.hibernate.generate_statistics=true
