spring.profiles.active = uat
#server.port=8080
#server.servlet.session.timeout=1
#hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.banner.location=classpath:banner.txt
application.version=2.0

default.password=Apmosys@123

## Leave Policy Reference Details
financialYear.startDate = 1
financialYear.startMonth = 4

#PO portal db details
po.db.url =jdbc:mysql://150.242.14.145:3306/PO_PORTAL
po.db.username =Jenkin
po.db.password =password

#Timesheet lock period
timesheet.lock.days = 3
timesheet.backdated.days = 30
timesheet.reconcile.days = 3

compoff.lock.days = 60
leave.backdated.lock.days = 60
leave.future.lock.days = 180

#Timesheet By Team member
timesheet.check.period = 30
maximum.timesheetCanBeFilledByMember = 2

#static OTP
portal.static.otp = 12341234

# OTP Timeout (Min)
otp.timeout.period = 1 

# User Idle Session timeout (Sec)
idle.session.timeout=900
revoke.reportee.leave.validity = 7

valid.attempt=5
usersession.inactive.timeout = 10

#mail
mail.sender = ishine@apmosys.com
mail.password = Welcome@2021
# mail.password = Welcome@2021  prod mail password
mail.port = 587
mail.host = apmosys.icewarpcloud.in

#hr mail address
hr.mail = ar731829@gmail.com
finance.mail = ar731829@gmail.com
rmg.mail = ar731829@gmail.com

#noticePeriod & probationPeriod MailTrigger time
mailTrigger.time = 0 0 12 ? * *
timesheetDefaulter.time = 0 0 14 ? * *

#monthlyTimesheetExcelGenerator CronExpression
monthlyTimesheetExcelGenerator.expression = 0 0 4 2 * ?
birthdaymail.cron.expression = 0 0 7 ? * *

CLleave.maxDays = 2

#   0 0 7 ? * *     //  this cron expression run daily on 7 O'clock at morning
compOff_TAT = 0 0 7 ? * *
#compOff_TAT = 0 */59 * * * ?
#spring.jpa.properties.hibernate.generate_statistics=true