#datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#schema that contains uat test data as per po uat portal projects
spring.datasource.url=jdbc:mysql://192.168.21.195:3306/emp_portal_db

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

#schema that contains latest prod data as of 19/08/2025
#spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_backup

#schema that contains last uat test data
## spring.datasource.url=jdbc:mysql://192.168.21.195:3306/emp_portal_db   

#uat
# spring.datasource.url=jdbc:mysql://192.168.21.195:3306/db_emp_portal
spring.data.mongodb.uri=mongodb://admin:Apmosys123@192.168.12.113:27017/ishine-mongodb?authSource=admin

spring.datasource.username=dbuser_emp_portal
spring.datasource.password=Apmosys@Emp123

meilisearch.host=http://localhost:7700  # or your Meilisearch server URL
meilisearch.apikey=masterKey

#Python OCR
pythonUrl.for.ocr=http://172.1.1.232:5000

project.insight.upload.directory=/app/files/uploads

#reverse sync api on approve 
#poPortal.api.syncProject =http://10.8.0.121:8080/ishine/sync
#poPortal.api.syncProject =http://172.1.3.174:8080/ishine/sync


meilisearch.host = http://localhost:7700
meilisearch.masterKey = masterKey





#Shankh Portal Prod
# poPortal.api.allProjects =https://shankh.apmosys.com/project/fixedCost/getAllProjects
# poPortal.api.getProjectById = https://shankh.apmosys.com/project/fixedCost/getResourceRequirementByProjectId
#poPortal.api.realtimeProjectData = http://192.168.21.175:8080/api/poCrudOperationsInIshine

#Shankh Portal Uat
#poPortal.api.allProjects =http://10.8.0.121:8080/project/fixedCost/getAllProjects

resignation.consent.link =http://192.168.21.175:8081/employeeportal/#/user-exit/my-resignation/
rmg.project.approval.link=http://192.168.21.175:8081/employeeportal/#/user-team/resource-management/
lms.redirectionURL=http://192.168.12.113/academy-lms/index.php/api/ishine
poPortal.api.realtimeProjectData = http://192.168.21.175:8080/api/poCrudOperationsInIshine
#QR code path
qr.storage.path=

#static OTP UAT
#portal.static.otp = 12341234
portal.static.otp = FxjCSxCuuAmeP8RJYKtpSat2omc1JFnyA+oQNr7DgsI=

#Delete Deparment PoPortal Sync Api
poPortal.api.syncDepartment = http://10.8.0.121:8080/ishine/updateDepartment/{id}
#poPortal.api.isDepartmentUsed = http://10.8.0.121:8080/ishine/isDepartmentUsed/
# poPortal.api.deleteDepartment = http://10.8.0.121:8080/ishine/deleteDepartment/

#Delete JobRole PoPortal Sync Api
# poPortal.api.syncJobRole =http://10.8.0.121:8080/ishine/updateRole/{id}
# poPortal.api.isJobRoleUsed = http://10.8.0.121:8080/ishine/isRoleUsed/

# poPortal.api.deleteJobRole = http://10.8.0.121:8080/ishine/deleteRole/

# poPortal.api.getFCLineItemDetails = http://10.8.0.121:8080/ishine/getFcLineItemDetails/

# Testing Started -------------------------------------------------------
#local
#poPortal.api.isJobRoleUsed =http://172.1.20.61:8080/ishine/isRoleUsed/
#poPortal.api.getFCLineItemDetails = http://172.1.20.61:8080/ishineDB/getFcLineItemDetails/
#poPortal.api.deleteJobRole = http://172.1.20.61:8080/ishine/deleteRole/
#poPortal.api.syncJobRole =http://172.1.20.61:8080/ishine/updateRole/
#poPortal.api.deleteDepartment = http://172.1.20.61:8080/ishine/deleteDepartment/
#poPortal.api.getProjectById = http://172.1.20.61:8080/po/tnm/getAllResourceRequirementByProjectId/
#poPortal.api.allProjects =http://172.1.20.61:8080/project/fixedCost/getAllProjects
#poPortal.api.syncProject =http://172.1.20.61:8080/ishine/sync
#poPortal.api.getcount =http://172.1.20.61:8080/po/tnm/getResourceRequirementCountByProjectId/
#poPortal.api.isDepartmentUsed = http://172.1.20.61:8080/ishine/isDepartmentUsed/
#poPortal.api.getMilestoneDoc =  http://172.1.20.61:8080/ishineDB/getMilestoneImageById/
#poPortal.api.updateMilestones=http://172.1.20.61:8080/ishineDB/updateMilestoneById

#UAT
poPortal.api.getMilestoneDoc =  http://10.8.0.121:8080/ishineDB/getMilestoneImageById/
poPortal.api.isJobRoleUsed = http://10.8.0.121:8080/ishine/isRoleUsed/
poPortal.api.getFCLineItemDetails = http://10.8.0.121:8080/ishineDB/getFcLineItemDetails/
poPortal.api.deleteJobRole = http://10.8.0.121:8080/ishine/deleteRole/
poPortal.api.syncJobRole =http://10.8.0.121:8080/ishine/updateRole/
poPortal.api.deleteDepartment = http://10.8.0.121:8080/ishine/deleteDepartment/
poPortal.api.getProjectById = http://10.8.0.121:8080/po/tnm/getAllResourceRequirementByProjectId/
poPortal.api.allProjects =http://10.8.0.121:8080/project/fixedCost/getAllProjects
poPortal.api.syncProject =http://10.8.0.121:8080/ishine/sync
poPortal.api.getcount = http://10.8.0.121:8080/po/tnm/getResourceRequirementCountByProjectId/
poPortal.api.isDepartmentUsed = http://10.8.0.121:8080/ishine/isDepartmentUsed/
poPortal.api.updateMilestones=http://10.8.0.121:8080/ishineDB/updateMilestoneById
poPortal.api.getAllMailsByProjectId=http://192.168.21.175:8080/ishineDB/getAllMailsByProjectId/
poPortal.api.getAllPoOfProjects=http://10.8.0.121:8080/project/tnm/getAllProjectPoMappingAndResourceDetails
poPortal.api.getSDEDOfProjects=http://10.8.0.121:8080/ishine/setProjectDatesAndSyncToIshine
poPortal.api.syncCLientDetails=http://10.8.0.121:8080/client/syncCLientDetails
# Testing End------------------------------------------------------------


file.location.upload-dir=/home/apmosys/tomcat-app/tomcat-emp/webapps/surveymedia/
file.location.image=/home/apmosys/tomcat-app/tomcat-emp/webapps/imagess/
file.location.document=/home/apmosys/tomcat-app/tomcat-emp/webapps/document/
helpFile.document.location = /home/apmosys/tomcat-app/tomcat-emp/webapps/helpDocument
file.location.releasenotesvideos= /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/video/
file.location.releasenotevideos= /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/video/
#file.location.releasenotesvideosOut=../../assets/videosTest/
file.location.documents.newsletter = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/newsletter
file.location.documents.travelDesk = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/travelDesk
file.location.documents.reimbursement = /home/apmosys/tomcat-app/tomcat-emp/webapps/documents/reimbursement


file.location.documents.training = /home/rishabh.verma@apmosys.mahape/Music/Training_Files
file.training.max.size.allowed=30MB
#file location for Fcmilestone
#file.location.documents.fcmilestone=/home/apmosys/tomcat-app/tomcat-emp/webapps/documents/fcmilestone
training.job.role.exclude = 1, 111

file.location.documents.fcmilestone=/home/dibyaranjan.das@apmosys.mahape/uploads/milestones


#poPortalMilestoneExpiry
poPortal.api.milestoneExpiry=http://192.168.21.175:8080/ishineDB/getAllExpiringMilestones
poPortal.api.updateMilestoneExtendedDate=http://192.168.21.175:8080/ishineDB/extendMilestoneDate

spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

hr.mail = pratiksha.raorane@apmosysuat1.com
finance.mail =  nidhi.pote@apmosysuat1.com
#rmg.mail = neha.borase@apmosys.com,pratiksha.raorane@apmosys.com,subhalaxmi.behera@apmosys.com
rmg.mail = priyadarshini.singh@apmosysuat1.com
billable.mail = neha.borase@apmosysuat1.com,pratiksha.raorane@apmosysuat1.com,subhalaxmi.behera@apmosysuat1.com
vp_mails = neha.borase@apmosysuat1.com,pratiksha.raorane@apmosysuat1.com,subhalaxmi.behera@apmosysuat1.com
bd.mail = pratikshya.routray@apmosysuat1.com
admin.mail = priyadarshini.singh@apmosysuat1.com
billablechange.mail = prarthana.lenka@apmosysuat1.com
ticket.mail = om.padwal@apmosysuat1.com
admin.head = om.padwal@apmosysuat1.com
hr.head = prarthana.lenka@apmosysuat1.com
#10 minutes wait time
#spring.datasource.hikari.maxLifeTime : 180000

#Connection pool
#maximum number of milliseconds that a client will wait for a connection
spring.datasource.hikari.connection-timeout = 150000
#minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.minimum-idle= 10
#maximum pool size
spring.datasource.hikari.maximum-pool-size= 3000
#maximum idle time for connection
spring.datasource.hikari.idle-timeout=100000
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
spring.datasource.hikari.max-lifetime= 180000

FilterSqlFields =  Delivery_Mode, Clients, Created_At, tech_stack
FilterMongodbFields = tags

#For Travel Allowance data
level2Approver = 2

#For Reimbursement data
level2.Approver = 632
level2.ApproverMail = hrm2@apmosysemp.com
level3.Approver = 9
level3.ApproverMail = lituja.mishra@apmosysemp.com

allEmployeeDSR.file.location=/home/apmosys/tomcat-app/tomcat-emp/webapps/

#Logging properties
#logging.file.name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#logging.pattern.console=[%thread] %d{yyyy-MM-dd HH:mm:ss} - %msg%n 
#logging.file.max-size=5MB
#logging.pattern.rolling-file-name=/home/apmosys/tomcat-app/tomcat-emp/webapps/logs/ishineportal-%d{yyyy-MM-dd}.%i.log
#logging.file.max-history=7


#DMS PORTAL APIs
dmsPortalUrl=http://192.168.12.114/dmsportal/api/external
dmsPortalUrlKey=fec99190ec32a48402330ebe7890af95f369511941d03de18eb0c27a97042024

log.path=/home/apmosys/Documents/LatestWorkSpace/Rewamp_Cleaning/logs
#log.path =/home/apmosys/tomcat-app/tomcat-emp/logs
#log.file.name=ishineportal.log
# Log file location

log.file.name=ishineportal.log
#log.path=/home/

## Rolling policy
#logging.file.max-size=5MB
#logging.file.max-history=7
#
## Logging pattern
#log.pattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n
#
## Root log level
#log.root.level=INFO
#
## Enable console logging for ERROR only
#log.console.enabled=true
#log.console.level=ERROR

#############################
leavetypeId = 1

#Correct mail password
mail.password = Welcome@2021

#InCorrect mail password
#mail.password = Welcome@2022

#OTP rate Limiting
otp.max.failed.attempts=5
otp.cooldown.minutes=15
otp.max.requests.per.hour=5

EXPIRY_THRESHOLD_PERCENT = 80


#server secure settings
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

dmsPortalUploadUrlKey=fec99190ec32a48402330ebe7890af95f369511941d03de18eb0c27a97042024
dmsPortalFetchUrlKey=22a959377645dd28ca052a7f21acdcccc1365f07032d60e505505785b89962b1

upload.path = /home/apmosys/tomcat-app/tomcat-emp/ishine-image
hr.head = lituja.mishra@apmosysuat1.com






timesheet.minus.days.for.bulk.upload = 45
# toggle for timesheet minus days for bulk upload, true -> It will check minus days, false -> It will not check minus days
check.minus.days.for.bulk.upload = true
timesheet.max.file.size = 10MB
