package com.apmosys.employeeportal.dto.TimesheetDTO_new;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;


import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing employee-level timesheet data.
 * One EmployeeTimesheet per day per employee.
 * Maps to: employee_timesheets_new table
 * 
 * @author System
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EmployeeTimesheetDTO {

    /**
     * Primary key - Timesheet ID
     * Auto-generated by database
     */
    private Long timesheetId;

    /**
     * Employee ID (FK to employee table)
     * Required for creation
     */
    private Long empId;

    /**
     * Timesheet date
     * Required for creation
     * Cannot be in future
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate date;

    /**
     * Day Type ID (FK to day_type_master_new)
     * Required for creation
     * Examples: 1=Working, 2=Week Off, 3=Public Holiday, 4=Leave, etc.
     */
    private Integer dayTypeId;

    /**
     * Leave Type ID (FK to leave_type_master)
     * Optional - only required if dayTypeId indicates Leave
     */
    private Long leaveTypeId;

    /**
     * Status - Calculated logically from project statuses
     * Values: 1=Pending, 2=Approved, 3=Rejected, 4=Partial
     * This is calculated, not directly set
     */
    private Integer status;

    /**
     * Total working minutes
     * Calculated from officeInTime and officeOutTime
     * Or sum of activity durations if office times not provided
     */
    private Integer totalWorkingMinutes;

    /**
     * Total activities minutes
     * Sum of all durationMinutes from all activities across all projects
     * Calculated automatically
     */
    private Integer totalActivitiesMinutes;

    /**
     * Created by user ID
     * Set automatically from current user context
     */
    private Long createdBy;

    /**
     * Created timestamp
     * Set automatically
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdOn;

    /**
     * Updated by user ID
     * Set automatically from current user context
     */
    private Long updatedBy;

    /**
     * Updated timestamp
     * Set automatically
     */
    private String description;
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedOn;
        
    /**
     * Work check-in time (format: "HH:mm" or "HH:mm:ss")
     * NEW CONTRACT: Maps to officeInTime
     * Example: "09:00"
     * Required for working days
     */
    private String workCheckIn;
    
    /**
     * Work check-out time (format: "HH:mm" or "HH:mm:ss")
     * NEW CONTRACT: Maps to officeOutTime
     * Example: "18:30"
     * Required for working days
     */
    private String workCheckOut;
    
    /**
     * Day type as string (e.g., "Working", "Week Off", "Leave")
     * NEW CONTRACT: Maps to dayTypeId
     * Required for creation
     */
    private String dayType;
    
    /**
     * Is night shift
     * NEW CONTRACT: Boolean flag for night shift
     * Optional - defaults to false
     */
    private Boolean isNightShift;
    
    /**
     * Current manager ID
     * NOT IN NEW CONTRACT but kept for business logic
     * Used for approval workflows
     */
    private Long currentManagerId;
    
    /**
     * Is Apmosys product flag
     * NOT IN NEW CONTRACT but kept for business logic
     * Used for product-specific timesheet rules
     */
    private String isApmosysProduct;
    
    /**
     * Location sessions - NEW CONTRACT STRUCTURE
     * Multiple location sessions per day (e.g., Office 9:00-13:00, Client Site 14:00-18:00)
     * Each location session contains projects and activities
     * Required for working days
     */
    private List<LocationSessionDTO> locationSessions;
    
    /**
     * Document data - NEW CONTRACT STRUCTURE
     * List of documents associated with timesheet projects
     * Optional - for attendance proof and approval documents
     */
    private List<TimesheetDocumentDataDTO> documentData;
}

