package com.apmosys.employeeportal.dto.TimesheetDTO_new;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.jetbrains.annotations.NotNull;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing employee-level timesheet data.
 * One EmployeeTimesheet per day per employee.
 * Maps to: employee_timesheets_new table
 * 
 * @author System
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EmployeeTimesheetDTO {

    /**
     * Primary key - Timesheet ID
     * Auto-generated by database
     */
    private Long timesheetId;

    /**
     * Employee ID (FK to employee table)
     * Required for creation
     */
    @NotNull("Employee ID is required")
    private Long empId;

    /**
     * Timesheet date
     * Required for creation
     * Cannot be in future
     */
    @NotNull("Date is required")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate date;

    /**
     * Day Type ID (FK to day_type_master_new)
     * Required for creation
     * Examples: 1=Working, 2=Week Off, 3=Public Holiday, 4=Leave, etc.
     */
    @NotNull("Day Type ID is required")
    private Integer dayTypeId;

    /**
     * Leave Type ID (FK to leave_type_master)
     * Optional - only required if dayTypeId indicates Leave
     */
    private Long leaveTypeId;

    /**
     * Status - Calculated logically from project statuses
     * Values: 1=Pending, 2=Approved, 3=Rejected, 4=Partial
     * This is calculated, not directly set
     */
    private Integer status;

    /**
     * Total working minutes
     * Calculated from officeInTime and officeOutTime
     * Or sum of activity durations if office times not provided
     */
    private Integer totalWorkingMinutes;

    /**
     * Total activities minutes
     * Sum of all durationMinutes from all activities across all projects
     * Calculated automatically
     */
    private Integer totalActivitiesMinutes;

    /**
     * Office in time
     * Optional - for tracking office attendance
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime officeInTime;

    /**
     * Office out time
     * Optional - for tracking office attendance
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime officeOutTime;

    /**
     * Created by user ID
     * Set automatically from current user context
     */
    private Long createdBy;

    /**
     * Created timestamp
     * Set automatically
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdOn;

    /**
     * Updated by user ID
     * Set automatically from current user context
     */
    private Long updatedBy;

    /**
     * Updated timestamp
     * Set automatically
     */
    private String description;
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedOn;
    private List<ProjectTimesheetDTO> projectTimesheets;
}

