package com.apmosys.employeeportal.dto.TimesheetDTO_new;

import com.apmosys.employeeportal.model.TimesheetDocumentDetailsNew;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing document data for timesheet.
 * NEW CONTRACT: Document data is at employee level, linked to projects.
 * 
 * @author System
 * @version 2.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TimesheetDocumentDataDTO {

    /**
     * Document ID (null for new documents)
     * Auto-generated by database
     */
    private Long docId; 

    /**
     * Project ID this document is associated with
     * Required for creation
     */
    private Integer projectId;

    /**
     * Document name (e.g., "Screenshot_Approved", "Screenshot_Filled")
     * Required for creation
     */
    private String docName;

    /**
     * Final flag - true for approved documents, false for filled documents
     * Required for creation
     */
    private Boolean finalFlag;

    /**
     * Bulk approved document ID (for bulk approval scenarios)
     * Optional
     */
    private Long bulkApprovedDocId;

    /**
     * Unique identifier for document tracking
     * Optional
     */
    private String uniqueIdentifier;

    /**
     * Document Type -> "Filled", "Approved"
     * Required for creation
     */
    private String docType;

    public TimesheetDocumentDataDTO(TimesheetDocumentDetailsNew doc) {
        this.docId = doc.getDocId();
        this.projectId = doc.getProjectId();
        this.docName = doc.getDocName();
        this.finalFlag = doc.getFinalFlag();
        this.bulkApprovedDocId = doc.getBulkApprovedDocId();
        this.uniqueIdentifier = doc.getDocName();
        this.docType = doc.getFinalFlag() ? "Approved" : "Filled";
    }
}

