export class Leave{
    empId:any;
	leaveId:any;
	leaveTypeMasterId:any;
	leaveType:any;
	noOfDays:any;
	reason:any;
	fromDate:any;
	toDate:any;
	createdBy:any;
	createdOn:any;
	createdByName:any;
	managerId:any;
	status:any;
	leaveStatusId:any;
	leaveTypeCode:any;
	paidLeave:any;
	rules:any;
	description:any;
	balance:any;
	pendingForApproval:any;
	employeeLeaveList:any;
	compOffId:any;	
	compOffReasons:any;
	updateBalanceBy:any;
	message:any;
	compOffLeaveId:any;

	leaveAppliedFor:any;
	fromDateDayType:any;
	toDateDayType:any;
}